# Generated by Django 5.2.7 on 2025-10-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_hosting_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="crawled_at",
            new_name="created_at",
        ),
    ]
